import { ROLES, Role, MODULES, Module } from './types';

export const PERMISSIONS: Record<Role, Module[]> = {
  [ROLES.ADMIN]: [
    MODULES.DASHBOARD,
    MODULES.INSPECTIONS,
    MODULES.CALENDAR,
    MODULES.RECORDS,
    MODULES.ENTITIES,
    MODULES.STATISTICS,
    MODULES.USERS,
    MODULES.SALESFORCE_UPLOAD,
    MODULES.USER_UPLOAD,
    MODULES.ENTITY_UPLOAD,
  ],
  [ROLES.GESTOR]: [MODULES.DASHBOARD, MODULES.INSPECTIONS, MODULES.RECORDS, MODULES.CALENDAR],
  [ROLES.COLABORADOR]: [
    MODULES.DASHBOARD, 
    MODULES.INSPECTIONS, 
    MODULES.RECORDS,
    MODULES.CALENDAR,
  ],
  [ROLES.SOPORTE]: [
    MODULES.DASHBOARD, 
    MODULES.RECORDS, 
    MODULES.STATISTICS, 
    MODULES.SALESFORCE_UPLOAD,
    MODULES.CALENDAR,
  ],
  [ROLES.COORDINADOR_SSPP]: [
    MODULES.DASHBOARD,
    MODULES.INSPECTIONS,
    MODULES.CALENDAR,
    MODULES.RECORDS,
    MODULES.STATISTICS,
    MODULES.SALESFORCE_UPLOAD,
  ],
  [ROLES.CALIDAD]: [
    MODULES.DASHBOARD, 
    MODULES.RECORDS, 
    MODULES.SALESFORCE_UPLOAD,
    MODULES.CALENDAR,
  ],
  [ROLES.CANALES]: [
    MODULES.DASHBOARD, 
    MODULES.ENTITIES, 
    MODULES.RECORDS,
    MODULES.ENTITY_UPLOAD,
  ],
  [ROLES.VISUAL]: [MODULES.DASHBOARD, MODULES.RECORDS, MODULES.STATISTICS, MODULES.CALENDAR],
};
