import { ROLES, Role, MODULES, Module } from './types';

export const PERMISSIONS: Record<Role, Module[]> = {
  [ROLES.ADMIN]: [
    MODULES.DASHBOARD,
    MODULES.INSPECTIONS,
    MODULES.CALENDAR,
    MODULES.RECORDS,
    MODULES.ENTITIES,
    MODULES.STATISTICS,
    MODULES.USERS,
  ],
  [ROLES.GESTOR]: [MODULES.DASHBOARD, MODULES.INSPECTIONS, MODULES.RECORDS],
  [ROLES.COLABORADOR]: [MODULES.DASHBOARD, MODULES.INSPECTIONS, MODULES.RECORDS],
  [ROLES.SOPORTE]: [MODULES.DASHBOARD, MODULES.RECORDS, MODULES.STATISTICS],
  [ROLES.CALIDAD]: [MODULES.DASHBOARD, MODULES.RECORDS],
  [ROLES.CANALES]: [MODULES.DASHBOARD, MODULES.ENTITIES, MODULES.RECORDS],
  [ROLES.VISUAL]: [MODULES.DASHBOARD, MODULES.RECORDS, MODULES.STATISTICS],
};
