// This file is automatically generated. Do not modify it manually.
import type {FirebaseOptions} from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: 'studio-2874147398-14137',
  appId: '1:603471231506:web:0ac99ab0d72aa71b1336cb',
  apiKey: 'AIzaSyBEgDZCJx6xuqHzIhxDIcqCQgWZBXziio8',
  authDomain: 'studio-2874147398-14137-79dc1.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '603471231506',
};
